### ISSUE TITLE
John Smith Stash

### ISSUE THREAD

**Issue by Oddface** [John-Smith-Modded/JSTR-Modded-1.7.x#138]
Could we create a repo where we can stash unused textures? It doesn't always make sense to keep everything as alts, but we could still want to have them available for future use. We could put the alt texture sheets and customizer files (https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/80) in there as well. It could be a useful resource for texturers.

**Comment by ScottKillen** [comment]
We could, or we could create an orphaned branch in the repo with a completely different file structure.

**Comment by lesdmark** [comment]
Sounds useful and would trim down the pack which can only be a good thing

**Comment by ScottKillen** [comment]
I will set it up.

**Comment by lesdmark** [comment]
Sweet! :smile:

**Comment by ScottKillen** [comment]
I have created the new branch. It is located here: https://github.com/John-Smith-Modded/JSTR-1.7.x/tree/trove

**Comment by Oddface** [comment]
Well, I was thinking of this more as a resource for texture artists and not a collection of alts. If we're going to put all the alts in there we also need to somehow distribute it and make it available to users.

**Comment by ScottKillen** [comment]
I was thinking of this as a place for contributor resources...things that don't make into the pack but could be useful to those making textures.

**Comment by Oddface** [comment]
Yeah.

**Comment by Oddface** [comment]
Having it as a branch is proving to be a little unwieldy for me. I think having it as a separate repo will make it easier to access and also more visible to people.

**Comment by ScottKillen** [comment]
Try this: If is works and you like it, I can add intructions to the readme in that branch:

1. Make a second clone of the repo in another working directory.
2. In that clone's working folder, check out the trove branch.

You now have one working directory for the textures (the main repo) and one working directory for the assets (the second branch behaving like a second repo).

This is how I organized my work area.

For me, another repo would look the same on my workstation, but with the added disadvantage of having to follow two repo histories...

But I understand that I am a developer and my workflow might not work for everyone else, so I will raise no objections if a new repo is created.

**Comment by lesdmark** [comment]
I misunderstood the purpose of it. My bad. Figuring out a good long term solution to having a lot of alts should be something we think about as the pack is getting quite big.

**Comment by ScottKillen** [comment]
I also just remembered that the contributing instructions for this repo instruct folks to delete their fork and refork after contributing...and so this might make things more unwieldy. I never delete my fork.

**Comment by lesdmark** [comment]
I forgot that was what that said as well. That could make for some ickyness.
