### ISSUE TITLE
Ore overhaul

### ISSUE THREAD

**Issue by Oddface** [John-Smith-Modded/JSTR-Modded-1.7.x#140]
I've been experimenting a bit with the ores lately. There are a lot of weird inconsistencies in how the ores are done in the standard pack. I think a more clear style would make it easier for people to make ore textures as well as make overlay textures in mods like underground biomes work better. We should also bring the standard ores and the Legacy ores more in line with each other so that they can use the same nether ore textures and overlay textures without creating inconsistencies. I started creating overlays from the Legacy ores, cleaning them up and rounding off a bit. I think it's yielding mostly decent results. I'm trying to make JSTR style textures based on them as well.
Here are some copper textures:
![copper](https://cloud.githubusercontent.com/assets/7591428/11783492/e2a0a756-a277-11e5-9d7d-9fa70cea4fa3.png) ![copperuniversal](https://cloud.githubusercontent.com/assets/7591428/11783498/ecbacc3a-a277-11e5-9184-23fbe880c6e3.png)
Some overlay examples from underground biomes (including edge cases)
![blackgraniteoverlay](https://cloud.githubusercontent.com/assets/7591428/11783691/ccbb1330-a278-11e5-97b1-d3bb3cc02be4.png) ![chertoverlay](https://cloud.githubusercontent.com/assets/7591428/11783692/ccbebb8e-a278-11e5-974f-1337c792cf51.png) ![daciteoverlay](https://cloud.githubusercontent.com/assets/7591428/11783690/ccba7ef2-a278-11e5-9116-82a9fc295cb1.png) ![marbleoverlay](https://cloud.githubusercontent.com/assets/7591428/11783689/ccba8af0-a278-11e5-8a29-4cd4bfcc3dec.png)

Thoughts?

**Comment by ScottKillen** [comment]
:+1:

**Comment by Oddface** [comment]
Some more examples.
![legacylead](https://cloud.githubusercontent.com/assets/7591428/11815922/56a8b464-a34e-11e5-89d2-2cd96cf3f7c2.png) ![universallead](https://cloud.githubusercontent.com/assets/7591428/11815924/58425e9c-a34e-11e5-90a1-6ab812e0c33d.png)
![legacytin](https://cloud.githubusercontent.com/assets/7591428/11815928/5d14b726-a34e-11e5-8e04-925e8f36528b.png) ![universaltin](https://cloud.githubusercontent.com/assets/7591428/11815931/5f417a16-a34e-11e5-8e64-aa02411c1b29.png)
I think it's ok for overlays, legacy ores and jstr ores to have differences, as long as they keep the same general color and shape. Here I rounded off the tin overlay so that it wouldn't blend it with even the most similar rock type. It's still a little messy, but visible.
![tinoverlayexample](https://cloud.githubusercontent.com/assets/7591428/11815936/6227af20-a34e-11e5-89a7-98c33f07a3f2.png)
I'm posting some jstr ores here as examples, but I would prefer someone with more enthusiasm for that style work with them. I'll be focusing on finishing the overlays for now.

**Comment by lesdmark** [comment]
I like the fact that copper is redish orange again the biggest trick I have discovered is making sure the ore doesn't look like it's sitting on top of the texture below it.

**Comment by Oddface** [comment]
Here are some new versions of copper, tin, lead and nickel.
![universalcopper](https://cloud.githubusercontent.com/assets/7591428/12920781/57375ff2-cf4a-11e5-902d-d13f33fd6cae.png) ![universaltin](https://cloud.githubusercontent.com/assets/7591428/12920914/00c36a5c-cf4b-11e5-9158-6a25744a33fe.png) ![universallead](https://cloud.githubusercontent.com/assets/7591428/12920787/5cb348a6-cf4a-11e5-8164-f33c00a69fff.png) ![universalnickel](https://cloud.githubusercontent.com/assets/7591428/12928522/278eb98e-cf6e-11e5-9445-611561545824.png)
