### ISSUE TITLE
outdated railcraft texture for limiter track

### ISSUE THREAD

**Issue by Gwolfski** [John-Smith-Modded/JSTR-Modded-1.7.x#142]
the texture for railcraft's limiter
rail is broken (out of date). I have attached a link to the one which I
tried to fix. It works for me.

Link: http://i.imgur.com/1Rrr4Ac.png
Ingame screenshot: http://i.imgur.com/HW1hLwK.png

**Comment by Oddface** [comment]
This was fixed a while ago, but the pack hasn't been updated. https://github.com/John-Smith-Modded/JSTR-1.7.x/commit/c4a3096b7eb48f0ffa1a56a0b25584e32a593484

**Comment by ScottKillen** [comment]
Seems to have been fixed.
