### ISSUE TITLE
trouble joining the team

### ISSUE THREAD

**Issue by EdwardFlyhieght** [John-Smith-Modded/JSTR-Modded-1.7.x#143]
I would like to join the team however i'm having trouble with github. iv'e never used it before and i'm having trouble understanding it. i would like to add my Aether 2 pack that I've  updated and added to I would also help with whatever else i could. is their anyone how could help me?

**Comment by Oddface** [comment]
Download and install GitHub Desktop. Click the button on https://github.com/John-Smith-Modded/JSTR-1.7.x next to Download ZIP that saves the repo to your computer. The whole repository will be put in a folder and you can work with the files and folder structure there. When you've made your changes, you can use GitHub Desktop to commit them and then submit a pull request to get your changes into the pack.

**Comment by EdwardFlyhieght** [comment]
Thanks Oddface this was really helpful. I was able to commit them. however i'm having trouble with the last pull request part

**Comment by Oddface** [comment]
The create pull request button is up in the right hand corner. Once you've created it you can click on Sync to send it. I think that's how it works anyway. Haven't used it myself.

**Comment by EdwardFlyhieght** [comment]
I don't know why, but it will not work for me. keeps saying I don't have permission. do I have to be a Member?

**Comment by Oddface** [comment]
Anyone should be able to make a pull request. I don't think you need the sync button actually. Just click send pull request.

**Comment by EdwardFlyhieght** [comment]
am I suppose to type anything particular to address it when i pull request? maybe that's what i'm doing wrong.

**Comment by Oddface** [comment]
I really don't know much about GitHub either, other than the bare essentials. I guess you need to create a branch first, make commits to that, and then do a pull request.

**Comment by damonmensch** [comment]
Yeah direct pushing to the repository is closed to those not in the contributor team, however you can make a fork, push to your fork then submit a pull request.

**Comment by EdwardFlyhieght** [comment]
i thought so. i'll give it a go. but the this git hub is very new too me. so how does one join the contributor team?

**Comment by ScottKillen** [comment]
You can contribute by following a [simple process](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/). You don't actually have to be a member of the contributor team.

The contributor team has the necessary privileges to make decisions about the direction of the pack and so it is limited...but members of the team can also do a lot of damage that is difficult to reverse...
