### ISSUE TITLE
Updates (and the lack thereof)

### ISSUE THREAD

**Issue by Oddface** [John-Smith-Modded/JSTR-Modded-1.7.x#149]
This has been mentioned in a few times, so I'm making a new issue for it. The packs are not being updating often enough right now and it's been over 4 months since the last time. The current system relies on @goldbattle doing it manually, which has worked fine in the past, but I feel he's being a bit of an absent parent to us right now. I'm requesting we get some kind of automated updating system. It could be once a month, once a week or every time we commit, but we need something. I'm not code-savvy at all, so I need some help with the specifics here.

**Comment by artdude543** [comment]
Gold has had a lot of work on, along with education. I'm assuming you want the same thing like Soartex's system? Built midnight each day and pushed to various locations.

**Comment by artdude543** [comment]
If I created the server script for you guys on the same method as ours issue #144 would be needed. So might be a good idea.

**Comment by Oddface** [comment]
Cool :+1: 
Guess we have some work to do then.

**Comment by artdude543** [comment]
What CDN are you guys using? Or using CurseForge for the downloads at the mo?

**Comment by Oddface** [comment]
I think it's just curse.

**Comment by damonmensch** [comment]
So we just need the jsons for your script to work?

**Comment by artdude543** [comment]
Hmm okay will chat to Curse about getting a CDN for you guys. Or piggy back of Soartex's CDN. Yes the JSON files are what the scripts use [example](https://github.com/Soartex-Modded/Modded-1.8.x/blob/master/Igneous_Additions/mod.json). Also you can create custom modpack JSON's also ;) See [example](https://github.com/Soartex-Modded/Modded-Server-Data/tree/master/packs)

**Comment by damonmensch** [comment]
Personally I made for myself a batch script for Windows that copies the contents of the repository folders, ignoring the .git and overwrites folders into a single local, which I know is the first step for using Jenkins. However I know nothing about Jenkins to take it further.

**Comment by artdude543** [comment]
Yeah we tried a bunch of systems before settling on the JSON system. It's efficient and pretty much does all the work in less time than a person could. We handle about 100+ downloads and the script does it all w/o us lifting a finger and handles the version changes / deploys etc... ;)

**Comment by artdude543** [comment]
There is also a [mod](https://drone.io/github.com/Soartex-Modded/Mod-List-Builder/files) which generates modpack download JSON's for you. (Just requires naming changing etc.. buts the mods part will be pre-filled.

**Comment by damonmensch** [comment]
Looking at soartex, it appears that you guys have one fork and each mc version is a different branch,  would this work for our current setup or should we adapt to yours.

**Comment by artdude543** [comment]
We have a repo per version which allows back support to be easier. (The same is applied to the Vanilla repos). This also makes it easier for people to contribute as we don't want to alienate users with having to use a single repo with more than one branch for the textures. (That and we would hit GitHub's space limit for a repo)

**Comment by damonmensch** [comment]
Ok so it's set up the same way we have it

**Comment by damonmensch** [comment]
Sorry if asking too many questions, trying to get this squared away for us as seamlessly as possible. And once I know what we need I can get to setting it up for us.

I'd probably be more helpful here for the group since my skills align more with coding and back-end than graphic manipulation.

**Comment by artdude543** [comment]
He he no worries, I'll take care of the server side as all I need is to add a line to a JSON file to tell our server to build JSTR. So pretty much need you guys to handle the JSON's on here and for modpacks if needed. (But they will need to be added to our repo due to how the script works) We do have a Slack for this group to talk about this in more depth. Or I have a TS I don't mind you guys using to chat about things etc...

**Comment by damonmensch** [comment]
Mind inviting me to the Slack?

**Comment by artdude543** [comment]
@Oddface you mind me adding @damonmensch to the Slack?

**Comment by Oddface** [comment]
Of course not :)

**Comment by artdude543** [comment]
@damonmensch shoot me an email to invite you via :)

**Comment by damonmensch** [comment]
wenzel.dj@gmail.com Need to update my account to it anyway.

**Comment by artdude543** [comment]
Invite sent :)

**Comment by goldbattle** [comment]
Thanks for pushing this forward guys, ping me if you need permissions or
anything changed. Having it just push master builds to curse would work
perfectly, and the `mod.jsons` is a start in that direction. Thanks again
for picking up the slack.

**Comment by goldbattle** [comment]
To have things ease over, I have run my old script and uploaded some alpha builds. Let me know how these work for you guys.
http://minecraft.curseforge.com/projects/john-smith-legacy-modded/files

**Comment by ScottKillen** [comment]
Is the 1.7.10 release still being updated?

**Comment by lesdmark** [comment]
I have not personally touched it in a while, and I am pretty much the only one (besides yourself lately) who is doing anything to the pack at all.
