### ISSUE TITLE
Immersive Engineering - Metal Press & Plates

### ISSUE THREAD

**Issue by Naddox** [John-Smith-Modded/JSTR-Modded-1.7.x#156]
Using the latest alpha release with the patch, the metal press from IE looks good, but when you add a plate to it, its offset and oversized.

I have the gear press on mine when I noticed the graphical bug.

**Comment by Oddface** [comment]
Do you have a screenshot?

**Comment by ScottKillen** [comment]
Closed due to lack of response from requestor.
