### ISSUE TITLE
Garden Stuff Bloomery Furnace And His Gui Have Not Texture

### ISSUE THREAD

**Issue by murunid** [John-Smith-Modded/JSTR-Modded-1.7.x#157]
Please Add It ^_^

![45645456456465](https://cloud.githubusercontent.com/assets/18642654/14767467/7e0f931e-0a47-11e6-9c20-90d8cd6ce7a8.png)

**Comment by Oddface** [comment]
https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/commit/1fc68a96f48f1937db36a5d8f80b04703840b9f8
There you go. I actually did this a while ago, but never posted it for some reason.
