### ISSUE TITLE
Changing the default to Legacy textures

### ISSUE THREAD

**Issue by Oddface** [John-Smith-Modded/JSTR-Modded-1.7.x#161]
So, this idea has been discussed before, and has been met with some resistance from members of the team. However, I think it makes sense to do this now with the imminent relaunch. I've floated the idea on the FTB thread and while the poll turnout isn't big enough to say anything definitive, the response is leaning positive and there hasn't been any major pushback. Some people will have a strong preference for the current look, and we'll provide an overwrite pack for that. I've made the new cobblestone and stone bricks in a way that will work well with both JSTR and Legacy textures. It just makes sense for the default to be look John Smith settled on, and the look that's in the vanilla pack.

**Comment by ScottKillen** [comment]
This appears to be done and working great!
