### ISSUE TITLE
Additional Chisel Support

### ISSUE THREAD

**Issue by JetstormLP** [John-Smith-Modded/JSTR-Modded-1.7.x#163]
Any chance of us getting additional chisel support for the missing textures? I feel it is a heavily used mod but there seems to only be support for about 1/4 of the blocks.

**Comment by Oddface** [comment]
Chisel is just one of those mods that's most likely gonna stay incomplete, as doing all these unique aesthetic blocks in the John Smith style is really difficult and time consuming, and there's new stuff being added to it all the time. The transition to 1.9 is taking priority for me at the moment, but I do have some stone brick variations in the works, which I feel is the most basic thing in Chisel we don't have any support for.

**Comment by ScottKillen** [comment]
I use all the undefined textures to pull in some of those great decorative textures from other packs. (I include lots of metal blocks from all of the Wolfhound variants.)
