### ISSUE TITLE
AE2 Molecular Assembler Visual Bug

### ISSUE THREAD

**Issue by Tusque** [John-Smith-Modded/JSTR-Modded-1.7.x#167]
![the 1 7 10 pack](https://cloud.githubusercontent.com/assets/8241904/18613864/393437b8-7d51-11e6-9246-d290b85527d0.png)

Get this visual glitch with Molecular Assembler

**Comment by Tusque** [comment]
![johnsmith legacy modded - google chrome](https://cloud.githubusercontent.com/assets/8241904/18613959/f478e52c-7d52-11e6-860b-6f2bc38fa7e7.png)

I'm using this version, seeing it was last updated in 2015. New location to get the most up to date files? Not seeing any releases posted on github.

**Comment by artdude543** [comment]
You can find updated downloads here :) https://minecraft.curseforge.com/projects/john-smith-legacy-modded/files/2329485

**Comment by ScottKillen** [comment]
I'm closing this, making the assumption that a newer version worked out just fine... 😀
