### ISSUE TITLE
AE2 Purified Quartz Typo

### ISSUE THREAD

**Issue by Chubbychunks01** [John-Smith-Modded/JSTR-Modded-1.7.x#169]
Hey, this isn't a problem with a texture but a problem with the name of a texture. The Pure Nether, Fluix and Certus Quartz texture names all have typos, in the form of an extra "e". For example, the current name for the pure certus quartz is "ItemMaterial.Pur**e**ifiedCertusQuartzCrystal.png", but Purified only has one "e". The name should read "ItemMaterial.PurifiedCertusQuartzCrystal.png". 

I have a little resource pack I'm working on called "JSTR Tweaked!" where I use textures from the main Resource Pack and use them for mods not curently covered by this one, and I tested the name change and it worked.

**Comment by lesdmark** [comment]
I went ahead and corrected the mistake. Thanks for pointing it out!
