### ISSUE TITLE
Ae2 Only Gui's Working 1.10.2

### ISSUE THREAD

**Issue by VoidFyre** [John-Smith-Modded/JSTR-Modded-1.7.x#179]
I'm using the 1.10.2 version of the Modded Universal Pack on my custom modpack, which has the latest version of AE2 and only the GUI textures load.  The blocks and items still have the normal textures.

**Comment by Oddface** [comment]
I'm working on finishing the AE2 port right now. Almost done.

**Comment by VoidFyre** [comment]
Okay thank you. After playing dokucraft so long it got boring having so many mods with 16x textures

**Comment by Oddface** [comment]
👍 
By the way, future 1.10 bug reports should go here: https://github.com/John-Smith-Modded/JSTR-Modded-1.10.x
