### ISSUE TITLE
Kappa mode: steel block and slab uncraftable

### ISSUE THREAD

**Issue by donoya** [John-Smith-Modded/JSTR-Modded-1.7.x#186]
I'm trying to make the immersive engineering arc furnace to unlock dark steel and electrical steel and I can't seem to make the required parts. The steel block doesn't show up in NEI and the steel slab requires steel blocks, which the recipe shows requires immersive engineering steel. The only steel I can seem to make is the tinker's construct variety, even with the immersive engineering blast furnaces.

**Comment by ScottKillen** [comment]
This is the home of the John Smith Texture Pack. You might try reporting your issue [here](https://github.com/BluSunrize/ImmersiveEngineering).
