### ISSUE TITLE
Thaumcraft 4.2.3.X

### ISSUE THREAD

**Issue by alexguzman** [John-Smith-Modded/JSTR-Modded-1.7.x#45]
As of right now, a lot of textures are missing from Thaumcraft 4.2.2.1 (new items, etc.)

Also, almost all the GUIs could use a rework – definitely since most seem just to be pure upscales with no line redraw (no better than default).

**Comment by alexguzman** [comment]
Not 20 minutes after I say this, Thaumcraft has been updated to 4.2.3.0 ...

**Comment by damonmensch** [comment]
Looking in on this mod's textures it appears most of them are nothing more than just upscales.

**Comment by lesdmark** [comment]
If they are just upscales then we can get rid of them until someone has time to redo them right.

**Comment by damonmensch** [comment]
If anyone doing Thaumcraft needs them, I stumbled upon the original source used for the aspect icons.
May also be useful for other mods that also add aspects. http://game-icons.net/

**Comment by goldbattle** [comment]
Wow, nice find!

On Mon, Feb 9, 2015 at 12:03 PM, damonmensch <notifications@github.com>
wrote:

> If anyone doing Thaumcraft needs them, I stumbled upon the original source
> used for the aspect icons.
> May also be useful for other mods that also add aspects.
> http://game-icons.net/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/45#issuecomment-73546209>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by damonmensch** [comment]
I also found the [font he uses too](http://www222.pair.com/sjohn/temphis.htm), but that one is a purchase, which is why I didn't share sooner. I personally bought it.

**Comment by zHawky** [comment]
Im experience problems with Thaumcraft, when click researches game freeze (Forge10.13.4.1566, resourcepack downloaded from curse sept 11)
