### ISSUE TITLE
Flaxbeard's Steam Power support

### ISSUE THREAD

**Issue by Qohelethh** [John-Smith-Modded/JSTR-Modded-1.7.x#81]
I'm not sure if this is the right place to ask this, but is it possible that support for Flaxbeard's Steam Power will be added? It's a great mod and it's getting to be pretty popular.

**Comment by Oddface** [comment]
I started this a while back, but got distracted. I'm gonna try to finish it.

**Comment by Oddface** [comment]
Just committed the first batch of textures for this, hopefully before the new version of the pack is compiled. I ended up focusing on finishing the brass stuff to avoid inconsistency, and I got most of it done.

**Comment by Qohelethh** [comment]
Wow, awesome work, man! I started texturing some of them for my personal pack but you did a way better job.

**Comment by Oddface** [comment]
Bordissed did a fantastic job on this mod. It's now fully supported!

**Comment by Qohelethh** [comment]
No offense to Bordissed, who did a great job, but I feel like these new textures don't fit with the style of John Smith and certainly don't capture the feel of the original textures. The new textures are much too dark, and would fit better in a pack like Glimmer's Steampunk. In fact, the texture for the smasher has a simple copy-paste from one of Glimmer's textures.

I really liked the old textures you made, Oddface, and I'll continue using them. If I'm the only one who feels this way, maybe you could still keep them as alternative textures?

Also, this isn't all the textures for Flaxbeard's mod. Most of the textures for the exosuit and its parts are still missing.

**Comment by Oddface** [comment]
Oops, I guess I'll keep this open for a bit longer then. I guess it wouldn't hurt to keep my textures as alts. I'll get right on that.

**Comment by Oddface** [comment]
I guess it's a matter of taste first and foremost, but I just think the new textures are of a higher quality, so that's why I'm going with them. It's true that it's a little dark and steampunk-ish, but not in a way that is incompatible with the pack, in my opinion.

**Comment by Qohelethh** [comment]
The new version of FSP added modular steam tools, which as of now are un-textured. In addition, the exo-suit is still entirely unsupported by John Smith. Any chance this will be worked on?
